version: 0.2

env:
  parameter-store:
    PORT: "/cicd-demo/port"
    DOCKER_REGISTRY_USERNAME: "/cicd-demo/docker-registry/username"
    DOCKER_REGISTRY_PASSWORD: "/cicd-demo/docker-registry/password"
    DOCKER_REGISTRY_URL: "/cicd-demo/docker-registry/url"
    

phases:
  install:
    runtime-versions:
        nodejs: 20.11.0
    commands:
        - touch .env
        - echo "PORT=$PORT" >> .env
        - npm install
    
  build:
    commands:
        - echo Build started on `date`
        - echo Building docke image..
        - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/cicd-demo:latest"
        - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/cicd-demo:latest"
  
  post_build:
    command:
        - echo "Build is Successful"
artifacts:
  files:
    - '**/*'
  discard-paths: yes

